plugins {
    id 'com.android.application'
}

android {
    namespace 'com.scsonic.qwenimage21.demo'
    compileSdk 35

    defaultConfig {
        applicationId 'com.scsonic.qwenimage21.demo'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1'
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':qwenimage21')
}
